name: CI
on:
  push:
    branches:
      - blog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: blog		  
      - name: Configration hexo repo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "tangmen.cn@gmail.com"
          git config --global user.name "tiexo" 
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'		  
      - name: Setup Hexo
        run: |
         npm install hexo-cli -g
		     npm install gulp -g
         npm install 